/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import User

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    val user = User(name = "")
    println(user)
}
